### ISSUE TITLE
Song info not updated

### ISSUE THREAD

**Issue by WickedSik** [jblaker/SMUNativeAppWrapper#1]
I just installed the compiled app (downloadable via the README) and it works wonderfully, being a framed webpage, but the song information in the tooltip of the app does not update.

> Other than that, I love the app.

**Comment by jblaker** [comment]
For some reason every so often Sony changes the IDs of the elements the app targets for info. I'll get the new IDs and get this updated.

**Comment by jblaker** [comment]
Fixed in newest push
